name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist

    - name: Copy SSL folder
      run: |
        mkdir -p ${{ runner.temp }}/ssl
        cp -r ssl/ ${{ runner.temp }}/ssl

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hhhcinv'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ runner.temp }}
